### PR TITLE
Add pop-count exercise

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Review by kotp — APPROVED** [review]

**Comment by BNAndras** [comment]
The exercise name (not the slug itself) was updated recently in problem-specifications so I've accounted for that here. I also moved the exercise to the correct place within the track's exercise array.

**Review by kotp — APPROVED** [review]
Approving.  This seems to be setting the precedence of sorting by name, rather than slug?

**Comment by BNAndras** [comment]
Yeah, it'd make the most sense to sort by grouped difficulty and then exercise name. That largely matches what we have already done. We can't sort by slug at the moment because the slug for this exercise is `pop-count` but the user-facing name is Eliud's Eggs. It seems like Jeremy will fix the slug to match the name later.

**Comment by BNAndras** [comment]
@kotp, can I get a merge?

**Pull request merged**
