### PR TITLE
ETL exercise: provide hint to student to lowercase the letters

### PR DESCRIPTION
**Pull request by glennj**
For the merge comment, `[no important changes]` would be appropriate here: http://forum.exercism.org/t/maintainers-new-no-important-files-changed-flag-added/6500

### CODE REVIEW

**Comment by kotp** [comment]
Ah, we must have pressed the button at almost the exact same time... disregard.

**Comment by BNAndras** [comment]
I was wondering why the UI was glitching for me.

**Comment by glennj** [comment]
12 rep seems excessive for this PR. You could add the `x:rep/tiny` label.

**Comment by BNAndras** [comment]
Fixed. I didn't see a way to add labels through the mobile UI.

**Pull request merged**
