### PR TITLE
Add flatten-array exercise

### PR DESCRIPTION
**Pull request by BNAndras**
Related to #172

### CODE REVIEW

**Comment by BNAndras** [comment]
I changed the auto-generated tests to use v:null instead of an empty string. The exercise generator should be tweaked in the future if possible to use v:null so a future test sync doesn't break solutions for this exercise by reverting to an empty string representation.

**Comment by kotp** [comment]
> The exercise generator should be tweaked in the future if possible to use v:null so a future test sync doesn't break solutions for this exercise by reverting to an empty string representation.

Care to create an issue for that?

**Review by kotp — APPROVED** [review]

**Comment by BNAndras** [comment]
Yeah, I’ll file the issue.

**Comment by BNAndras** [comment]
Okay, my exercises for next month are all ready for your review.

**Review by kotp — APPROVED** [review]

**Pull request merged**
