### PR TITLE
Add list-ops

### PR DESCRIPTION
**Pull request by BNAndras**
Related to #172.

I have two bugs in my foldl/foldr implementation to resolve

### CODE REVIEW

**Comment by BNAndras** [comment]
For `folds (reduces) the given list from the left with a function -> direction dependent function applied to non-empty list` and `folds (reduces) the given list from the right with a function -> direction dependent function applied to non-empty list`, I used the older tests but updated the argument names to the newer ones (`elt` and `acc` instead of `x` and `y`).

**Comment by BNAndras** [comment]
@kotp, the `Reverse` from `reverse-string` is conflicting with the `Reverse` from here. There's already a single community solution for `reverse-string`. I can either break that solution and make `Reverse` be `ReverseString` in `reverse-string` or prefix the functions here with `My` like `MyAppend`, `MyReverse`, and so on.

**Comment by kotp** [comment]
> @kotp, the `Reverse` from `reverse-string` is conflicting with the `Reverse` from here. There's already a single community solution for `reverse-string`. I can either break that solution and make `Reverse` be `ReverseString` in `reverse-string` or prefix the functions here with `My` like `MyAppend`, `MyReverse`, and so on.

We could also use the word `reversal_of` or just `reversal`.

**Comment by BNAndras** [comment]
Works for me!

**Comment by kotp** [comment]
> Works for me!

Or `reverses(list)` or `reversed(list)`.

**Review by kotp — APPROVED** [review]

**Pull request merged**
